const btnProcess = document.getElementById("btnProcess");
const btnLoadSaved = document.getElementById("btnLoadSaved");
const inputStatus = document.getElementById("inputStatus");
const loadingOverlay = document.getElementById("loadingOverlay");
const resultsSection = document.getElementById("resultsSection");
const resultSource = document.getElementById("resultSource");
const accordion = document.getElementById("accordion");
const subtitleText = document.getElementById("subtitleText");
const btnProcessText = document.getElementById("btnProcessText");
const btnLoadSavedText = document.getElementById("btnLoadSavedText");
const loadingText = document.getElementById("loadingText");
const loadingSubText = document.getElementById("loadingSubText");
const resultsTitle = document.getElementById("resultsTitle");
const langVi = document.getElementById("langVi");
const langEn = document.getElementById("langEn");

const I18N = {
    vi: {
        subtitle: "Tự động sinh config cho 18 script Tampermonkey DS-160",
        btnProcess: "Xử lý dữ liệu từ thư mục /input",
        btnLoadSaved: "Tải kết quả đã lưu",
        loadingText: "Đang xử lý... AI đang phân tích dữ liệu và sinh config",
        loadingSub: "Quá trình này có thể mất 30-60 giây",
        resultsTitle: "Kết quả: {count} Script DS-160",
        sourceGenerated: "Mới tạo bởi AI",
        sourceSaved: "Đã lưu trước đó",
        tabConfig: "Config (JSON)",
        tabScript: "Full Script",
        copy: "Copy",
        copied: "Copied!",
        statusInputFound: "Tìm thấy {count} file (.docx/.pdf) trong /input: {files}",
        statusInputMissing: "Chưa tìm thấy file .docx hoặc .pdf nào trong thư mục /input. Hãy đặt file vào thư mục input/.",
        statusServerError: "Không thể kết nối đến server.",
        statusUnknownError: "Lỗi không xác định.",
        statusProcessSuccess: "Đã xử lý thành công! {count} script đã được tạo và lưu vào /output.",
        statusLoadSavedSuccess: "Đã tải kết quả từ /output.",
        statusLoadSavedMissing: "Chưa có kết quả đã lưu.",
        statusConnectError: "Lỗi kết nối: {error}",
    },
    en: {
        subtitle: "Automatically generate config for 18 DS-160 Tampermonkey scripts",
        btnProcess: "Process data from /input folder",
        btnLoadSaved: "Load saved results",
        loadingText: "Processing... AI is analyzing data and generating config",
        loadingSub: "This may take 30-60 seconds",
        resultsTitle: "Results: {count} DS-160 Scripts",
        sourceGenerated: "Generated by AI",
        sourceSaved: "Saved earlier",
        tabConfig: "Config (JSON)",
        tabScript: "Full Script",
        copy: "Copy",
        copied: "Copied!",
        statusInputFound: "Found {count} file(s) (.docx/.pdf) in /input: {files}",
        statusInputMissing: "No .docx or .pdf files found in /input. Please place input files in the input/ folder.",
        statusServerError: "Cannot connect to server.",
        statusUnknownError: "Unknown error.",
        statusProcessSuccess: "Processed successfully! {count} scripts were generated and saved to /output.",
        statusLoadSavedSuccess: "Loaded results from /output.",
        statusLoadSavedMissing: "No saved results yet.",
        statusConnectError: "Connection error: {error}",
    },
};

var currentLang = "vi";
var lastResultsData = null;
var lastStatus = null;

function t(key, params) {
    var text = (I18N[currentLang] && I18N[currentLang][key]) || key;
    if (!params) return text;
    Object.keys(params).forEach(function (paramKey) {
        text = text.replaceAll("{" + paramKey + "}", String(params[paramKey]));
    });
    return text;
}

function showStatus(message, type) {
    inputStatus.textContent = message;
    inputStatus.className = "status-bar visible " + type;
}

function showStatusByKey(key, type, params) {
    lastStatus = { key: key, type: type, params: params || {} };
    showStatus(t(key, params), type);
}

function showStatusRaw(message, type) {
    lastStatus = null;
    showStatus(message, type);
}

function hideStatus() {
    lastStatus = null;
    inputStatus.className = "status-bar";
}

function setLoading(on) {
    if (on) {
        loadingOverlay.classList.remove("hidden");
        btnProcess.disabled = true;
        btnLoadSaved.disabled = true;
    } else {
        loadingOverlay.classList.add("hidden");
        btnProcess.disabled = false;
        btnLoadSaved.disabled = false;
    }
}

function escapeHtml(str) {
    const div = document.createElement("div");
    div.appendChild(document.createTextNode(str));
    return div.innerHTML;
}

function setCopyButtonState(button) {
    button.textContent = t("copied");
    button.classList.add("copied");
    setTimeout(function () {
        button.textContent = t("copy");
        button.classList.remove("copied");
    }, 2000);
}

function copyText(text, button) {
    navigator.clipboard.writeText(text).then(function () {
        setCopyButtonState(button);
    });
}

function applyLanguage() {
    document.documentElement.lang = currentLang;
    subtitleText.textContent = t("subtitle");
    btnProcessText.textContent = t("btnProcess");
    btnLoadSavedText.textContent = t("btnLoadSaved");
    loadingText.textContent = t("loadingText");
    loadingSubText.textContent = t("loadingSub");
    resultsTitle.textContent = t("resultsTitle", { count: 18 });

    langVi.classList.toggle("active", currentLang === "vi");
    langEn.classList.toggle("active", currentLang === "en");

    if (lastResultsData) {
        renderResults(lastResultsData);
    }

    if (lastStatus) {
        showStatus(t(lastStatus.key, lastStatus.params), lastStatus.type);
    }
}

function renderResults(data) {
    const scripts = data.scripts;
    const source = data.source;
    lastResultsData = data;

    resultsSection.classList.remove("hidden");
    resultsTitle.textContent = t("resultsTitle", { count: scripts.length });

    if (source === "generated") {
        resultSource.textContent = t("sourceGenerated");
        resultSource.className = "badge generated";
    } else {
        resultSource.textContent = t("sourceSaved");
        resultSource.className = "badge saved";
    }

    accordion.innerHTML = "";

    scripts.forEach(function (item, idx) {
        var configJson = JSON.stringify(item.config, null, 2);
        var itemEl = document.createElement("div");
        itemEl.className = "accordion-item";

        itemEl.innerHTML =
            '<div class="accordion-header" data-idx="' + idx + '">' +
                '<span class="accordion-arrow">&#9654;</span>' +
                '<span class="accordion-title">' + escapeHtml(item.displayName) + '</span>' +
                '<div class="accordion-header-actions">' +
                    '<span class="accordion-filename">' + escapeHtml(item.filename) + '</span>' +
                    '<button class="accordion-copy-btn" type="button" data-copy-script="' + idx + '">' + t("copy") + '</button>' +
                '</div>' +
            '</div>' +
            '<div class="accordion-body">' +
                '<div class="accordion-content">' +
                    '<div class="tab-bar">' +
                        '<button class="tab-btn" data-tab="config-' + idx + '">' + t("tabConfig") + '</button>' +
                        '<button class="tab-btn active" data-tab="script-' + idx + '">' + t("tabScript") + '</button>' +
                    '</div>' +
                    '<div id="config-' + idx + '" class="tab-panel">' +
                        '<div class="code-container">' +
                            '<button class="copy-btn" data-copy="config-code-' + idx + '">' + t("copy") + '</button>' +
                            '<pre><code id="config-code-' + idx + '" class="language-json">' + escapeHtml(configJson) + '</code></pre>' +
                        '</div>' +
                    '</div>' +
                    '<div id="script-' + idx + '" class="tab-panel active">' +
                        '<div class="code-container">' +
                            '<button class="copy-btn" data-copy="script-code-' + idx + '">' + t("copy") + '</button>' +
                            '<pre><code id="script-code-' + idx + '" class="language-javascript">' + escapeHtml(item.fullScript) + '</code></pre>' +
                        '</div>' +
                    '</div>' +
                '</div>' +
            '</div>';

        accordion.appendChild(itemEl);
    });

    document.querySelectorAll(".accordion-header").forEach(function (header) {
        header.addEventListener("click", function () {
            var parent = this.parentElement;
            parent.classList.toggle("open");
        });
    });

    document.querySelectorAll(".accordion-copy-btn").forEach(function (btn) {
        btn.addEventListener("click", function (event) {
            event.stopPropagation();
            var scriptIdx = Number(this.getAttribute("data-copy-script"));
            var scriptItem = scripts[scriptIdx];
            if (!scriptItem) return;
            copyText(scriptItem.fullScript, this);
        });
    });

    document.querySelectorAll(".tab-btn").forEach(function (btn) {
        btn.addEventListener("click", function () {
            var targetId = this.getAttribute("data-tab");
            var tabBar = this.parentElement;
            var contentArea = tabBar.parentElement;

            tabBar.querySelectorAll(".tab-btn").forEach(function (b) { b.classList.remove("active"); });
            contentArea.querySelectorAll(".tab-panel").forEach(function (p) { p.classList.remove("active"); });

            this.classList.add("active");
            document.getElementById(targetId).classList.add("active");
        });
    });

    document.querySelectorAll(".copy-btn").forEach(function (btn) {
        btn.addEventListener("click", function () {
            var codeId = this.getAttribute("data-copy");
            var codeEl = document.getElementById(codeId);
            var text = codeEl.textContent;
            copyText(text, this);
        });
    });

    document.querySelectorAll("pre code").forEach(function (block) {
        hljs.highlightElement(block);
    });
}

async function checkInput() {
    try {
        var res = await fetch("/api/check-input");
        var data = await res.json();
        if (data.hasFiles) {
            showStatusByKey("statusInputFound", "success", {
                count: data.count,
                files: data.files.join(", "),
            });
        } else {
            showStatusByKey("statusInputMissing", "warning");
        }
    } catch (e) {
        showStatusByKey("statusServerError", "error");
    }
}

btnProcess.addEventListener("click", async function () {
    setLoading(true);
    hideStatus();

    try {
        var res = await fetch("/api/process", { method: "POST" });
        var data = await res.json();

        if (!res.ok) {
            showStatusRaw(data.detail || t("statusUnknownError"), "error");
            setLoading(false);
            return;
        }

        renderResults(data);
        showStatusByKey("statusProcessSuccess", "success", { count: data.scripts.length });
    } catch (e) {
        showStatusByKey("statusConnectError", "error", { error: e.message });
    }

    setLoading(false);
});

btnLoadSaved.addEventListener("click", async function () {
    setLoading(true);
    hideStatus();

    try {
        var res = await fetch("/api/output");
        var data = await res.json();

        if (!res.ok) {
            showStatusRaw(data.detail || t("statusLoadSavedMissing"), "warning");
            setLoading(false);
            return;
        }

        renderResults(data);
        showStatusByKey("statusLoadSavedSuccess", "info");
    } catch (e) {
        showStatusByKey("statusConnectError", "error", { error: e.message });
    }

    setLoading(false);
});

langVi.addEventListener("click", function () {
    currentLang = "vi";
    applyLanguage();
});

langEn.addEventListener("click", function () {
    currentLang = "en";
    applyLanguage();
});

applyLanguage();
checkInput();
